//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupPasswordShared
    {
        public int id { get; set; }
        public Nullable<int> id_group { get; set; }
        public Nullable<int> id_password { get; set; }
        public Nullable<int> id_permissions { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Login Login { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
