//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupUser
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> group_id { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
    }
}
