//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int id { get; set; }
        public string website { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string item_name { get; set; }
        public string note { get; set; }
        public Nullable<int> user_id { get; set; }
        public string email { get; set; }
    
        public virtual User User { get; set; }
    }
}
