//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteFile
    {
        public int id { get; set; }
        public Nullable<int> file_id { get; set; }
        public Nullable<int> note_id { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Note Note { get; set; }
    }
}
