//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TouristTour
    {
        public int Id { get; set; }
        public int TouristId { get; set; }
        public int TourId { get; set; }
    
        public virtual Tour Tour { get; set; }
        public virtual Tourist Tourist { get; set; }
    }
}
